version: "3.8"

services:
  # ----------------------------
  # PostgreSQL (for Notification Service)
  # ----------------------------
  postgres:
    image: postgres:16-alpine
    container_name: notification_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification_service_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notification-service-network
    restart: unless-stopped

  # ----------------------------
  # Redis (for Notification Service)
  # ----------------------------
  redis:
    image: redis:7-alpine
    container_name: notification_service_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notification-service-network
    restart: unless-stopped

  # ----------------------------
  # NATS (for Event Communication)
  # ----------------------------
  nats:
    image: nats:2.9.21-alpine
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - notification-service-network
    restart: unless-stopped

  # ----------------------------
  # Notification Service
  # ----------------------------
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "50058:50058"
    environment:
      # Database
      NOTIFICATION_DB_HOST: postgres
      NOTIFICATION_DB_PORT: 5432
      NOTIFICATION_DB_USER: postgres
      NOTIFICATION_DB_PASSWORD: postgres
      NOTIFICATION_DB_NAME: notification_service_db
      NOTIFICATION_DB_SSLMODE: disable

      # Redis
      REDIS_URL: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0

      # NATS
      NATS_URL: nats://nats:4222
      NATS_CLIENT_ID: notification-service

      # gRPC
      GRPC_PORT: 50058
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_started
    networks:
      - notification-service-network
    restart: unless-stopped

# ----------------------------
# Networks
# ----------------------------
networks:
  notification-service-network:
    driver: bridge

# ----------------------------
# Volumes
# ----------------------------
volumes:
  pgdata:
  redis_data:
