version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: post_service_db
    environment:
      POSTGRES_AUTH: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_service_db  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - post-service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  post-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post-service
    ports:
      - "50053:50053"
    environment:
      POST_DB_HOST: postgres
      POST_DB_PORT: 5432
      POST_DB_USER: postgres
      POST_DB_PASSWORD: postgres
      POST_DB_NAME: post_service_db
      POST_DB_SSLMODE: disable
      POST_DB_MAX_OPEN_CONNS: 25
      POST_DB_MAX_IDLE_CONNS: 5
      POST_DB_MAX_LIFETIME: 5m
      GRPC_PORT: 50053
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - post-service-network
    restart: unless-stopped

networks:
  post-service-network:
    driver: bridge

volumes:
  postgres_data:
