// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/like.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostRequest) Reset() {
	*x = LikePostRequest{}
	mi := &file_proto_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostRequest) ProtoMessage() {}

func (x *LikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostRequest.ProtoReflect.Descriptor instead.
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{0}
}

func (x *LikePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *LikePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UnlikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostRequest) Reset() {
	*x = UnlikePostRequest{}
	mi := &file_proto_like_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostRequest) ProtoMessage() {}

func (x *UnlikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostRequest.ProtoReflect.Descriptor instead.
func (*UnlikePostRequest) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{1}
}

func (x *UnlikePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UnlikePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPostLikesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PostId            string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	RequestingUserId  *string                `protobuf:"bytes,2,opt,name=requesting_user_id,json=requestingUserId,proto3,oneof" json:"requesting_user_id,omitempty"`
	RecentLikersLimit int32                  `protobuf:"varint,3,opt,name=recent_likers_limit,json=recentLikersLimit,proto3" json:"recent_likers_limit,omitempty"` // Default 5
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPostLikesRequest) Reset() {
	*x = GetPostLikesRequest{}
	mi := &file_proto_like_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostLikesRequest) ProtoMessage() {}

func (x *GetPostLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostLikesRequest.ProtoReflect.Descriptor instead.
func (*GetPostLikesRequest) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{2}
}

func (x *GetPostLikesRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetPostLikesRequest) GetRequestingUserId() string {
	if x != nil && x.RequestingUserId != nil {
		return *x.RequestingUserId
	}
	return ""
}

func (x *GetPostLikesRequest) GetRecentLikersLimit() int32 {
	if x != nil {
		return x.RecentLikersLimit
	}
	return 0
}

type IsPostLikedByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsPostLikedByUserRequest) Reset() {
	*x = IsPostLikedByUserRequest{}
	mi := &file_proto_like_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsPostLikedByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPostLikedByUserRequest) ProtoMessage() {}

func (x *IsPostLikedByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPostLikedByUserRequest.ProtoReflect.Descriptor instead.
func (*IsPostLikedByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{3}
}

func (x *IsPostLikedByUserRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *IsPostLikedByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsPostLikedByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLiked       bool                   `protobuf:"varint,1,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsPostLikedByUserResponse) Reset() {
	*x = IsPostLikedByUserResponse{}
	mi := &file_proto_like_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsPostLikedByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPostLikedByUserResponse) ProtoMessage() {}

func (x *IsPostLikedByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPostLikedByUserResponse.ProtoReflect.Descriptor instead.
func (*IsPostLikedByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{4}
}

func (x *IsPostLikedByUserResponse) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type GetPostLikesByUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostIds       []string               `protobuf:"bytes,1,rep,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostLikesByUsersRequest) Reset() {
	*x = GetPostLikesByUsersRequest{}
	mi := &file_proto_like_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostLikesByUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostLikesByUsersRequest) ProtoMessage() {}

func (x *GetPostLikesByUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostLikesByUsersRequest.ProtoReflect.Descriptor instead.
func (*GetPostLikesByUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{5}
}

func (x *GetPostLikesByUsersRequest) GetPostIds() []string {
	if x != nil {
		return x.PostIds
	}
	return nil
}

func (x *GetPostLikesByUsersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PostLikeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	IsLiked       bool                   `protobuf:"varint,2,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLikeStatus) Reset() {
	*x = PostLikeStatus{}
	mi := &file_proto_like_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLikeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLikeStatus) ProtoMessage() {}

func (x *PostLikeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLikeStatus.ProtoReflect.Descriptor instead.
func (*PostLikeStatus) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{6}
}

func (x *PostLikeStatus) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostLikeStatus) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type GetPostLikesByUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Likes         []*PostLikeStatus      `protobuf:"bytes,1,rep,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostLikesByUsersResponse) Reset() {
	*x = GetPostLikesByUsersResponse{}
	mi := &file_proto_like_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostLikesByUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostLikesByUsersResponse) ProtoMessage() {}

func (x *GetPostLikesByUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostLikesByUsersResponse.ProtoReflect.Descriptor instead.
func (*GetPostLikesByUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostLikesByUsersResponse) GetLikes() []*PostLikeStatus {
	if x != nil {
		return x.Likes
	}
	return nil
}

type LikeInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Count                int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	IsLikedByCurrentUser *bool                  `protobuf:"varint,2,opt,name=is_liked_by_current_user,json=isLikedByCurrentUser,proto3,oneof" json:"is_liked_by_current_user,omitempty"`
	RecentLikerIds       []string               `protobuf:"bytes,3,rep,name=recent_liker_ids,json=recentLikerIds,proto3" json:"recent_liker_ids,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LikeInfo) Reset() {
	*x = LikeInfo{}
	mi := &file_proto_like_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeInfo) ProtoMessage() {}

func (x *LikeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeInfo.ProtoReflect.Descriptor instead.
func (*LikeInfo) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{8}
}

func (x *LikeInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LikeInfo) GetIsLikedByCurrentUser() bool {
	if x != nil && x.IsLikedByCurrentUser != nil {
		return *x.IsLikedByCurrentUser
	}
	return false
}

func (x *LikeInfo) GetRecentLikerIds() []string {
	if x != nil {
		return x.RecentLikerIds
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_like_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{9}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_like_proto protoreflect.FileDescriptor

const file_proto_like_proto_rawDesc = "" +
	"\n" +
	"\x10proto/like.proto\x12\x04like\"C\n" +
	"\x0fLikePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"E\n" +
	"\x11UnlikePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xa8\x01\n" +
	"\x13GetPostLikesRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x121\n" +
	"\x12requesting_user_id\x18\x02 \x01(\tH\x00R\x10requestingUserId\x88\x01\x01\x12.\n" +
	"\x13recent_likers_limit\x18\x03 \x01(\x05R\x11recentLikersLimitB\x15\n" +
	"\x13_requesting_user_id\"L\n" +
	"\x18IsPostLikedByUserRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"6\n" +
	"\x19IsPostLikedByUserResponse\x12\x19\n" +
	"\bis_liked\x18\x01 \x01(\bR\aisLiked\"P\n" +
	"\x1aGetPostLikesByUsersRequest\x12\x19\n" +
	"\bpost_ids\x18\x01 \x03(\tR\apostIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"D\n" +
	"\x0ePostLikeStatus\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x19\n" +
	"\bis_liked\x18\x02 \x01(\bR\aisLiked\"I\n" +
	"\x1bGetPostLikesByUsersResponse\x12*\n" +
	"\x05likes\x18\x01 \x03(\v2\x14.like.PostLikeStatusR\x05likes\"\xa4\x01\n" +
	"\bLikeInfo\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12;\n" +
	"\x18is_liked_by_current_user\x18\x02 \x01(\bH\x00R\x14isLikedByCurrentUser\x88\x01\x01\x12(\n" +
	"\x10recent_liker_ids\x18\x03 \x03(\tR\x0erecentLikerIdsB\x1b\n" +
	"\x19_is_liked_by_current_user\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe4\x02\n" +
	"\vLikeService\x121\n" +
	"\bLikePost\x12\x15.like.LikePostRequest\x1a\x0e.like.Response\x125\n" +
	"\n" +
	"UnlikePost\x12\x17.like.UnlikePostRequest\x1a\x0e.like.Response\x129\n" +
	"\fGetPostLikes\x12\x19.like.GetPostLikesRequest\x1a\x0e.like.LikeInfo\x12T\n" +
	"\x11IsPostLikedByUser\x12\x1e.like.IsPostLikedByUserRequest\x1a\x1f.like.IsPostLikedByUserResponse\x12Z\n" +
	"\x13GetPostLikesByUsers\x12 .like.GetPostLikesByUsersRequest\x1a!.like.GetPostLikesByUsersResponseB\x04Z\x02./b\x06proto3"

var (
	file_proto_like_proto_rawDescOnce sync.Once
	file_proto_like_proto_rawDescData []byte
)

func file_proto_like_proto_rawDescGZIP() []byte {
	file_proto_like_proto_rawDescOnce.Do(func() {
		file_proto_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_like_proto_rawDesc), len(file_proto_like_proto_rawDesc)))
	})
	return file_proto_like_proto_rawDescData
}

var file_proto_like_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_like_proto_goTypes = []any{
	(*LikePostRequest)(nil),             // 0: like.LikePostRequest
	(*UnlikePostRequest)(nil),           // 1: like.UnlikePostRequest
	(*GetPostLikesRequest)(nil),         // 2: like.GetPostLikesRequest
	(*IsPostLikedByUserRequest)(nil),    // 3: like.IsPostLikedByUserRequest
	(*IsPostLikedByUserResponse)(nil),   // 4: like.IsPostLikedByUserResponse
	(*GetPostLikesByUsersRequest)(nil),  // 5: like.GetPostLikesByUsersRequest
	(*PostLikeStatus)(nil),              // 6: like.PostLikeStatus
	(*GetPostLikesByUsersResponse)(nil), // 7: like.GetPostLikesByUsersResponse
	(*LikeInfo)(nil),                    // 8: like.LikeInfo
	(*Response)(nil),                    // 9: like.Response
}
var file_proto_like_proto_depIdxs = []int32{
	6, // 0: like.GetPostLikesByUsersResponse.likes:type_name -> like.PostLikeStatus
	0, // 1: like.LikeService.LikePost:input_type -> like.LikePostRequest
	1, // 2: like.LikeService.UnlikePost:input_type -> like.UnlikePostRequest
	2, // 3: like.LikeService.GetPostLikes:input_type -> like.GetPostLikesRequest
	3, // 4: like.LikeService.IsPostLikedByUser:input_type -> like.IsPostLikedByUserRequest
	5, // 5: like.LikeService.GetPostLikesByUsers:input_type -> like.GetPostLikesByUsersRequest
	9, // 6: like.LikeService.LikePost:output_type -> like.Response
	9, // 7: like.LikeService.UnlikePost:output_type -> like.Response
	8, // 8: like.LikeService.GetPostLikes:output_type -> like.LikeInfo
	4, // 9: like.LikeService.IsPostLikedByUser:output_type -> like.IsPostLikedByUserResponse
	7, // 10: like.LikeService.GetPostLikesByUsers:output_type -> like.GetPostLikesByUsersResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_like_proto_init() }
func file_proto_like_proto_init() {
	if File_proto_like_proto != nil {
		return
	}
	file_proto_like_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_like_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_like_proto_rawDesc), len(file_proto_like_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_like_proto_goTypes,
		DependencyIndexes: file_proto_like_proto_depIdxs,
		MessageInfos:      file_proto_like_proto_msgTypes,
	}.Build()
	File_proto_like_proto = out.File
	file_proto_like_proto_goTypes = nil
	file_proto_like_proto_depIdxs = nil
}
