// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/post.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_proto_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetPostRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PostId           string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	RequestingUserId *string                `protobuf:"bytes,2,opt,name=requesting_user_id,json=requestingUserId,proto3,oneof" json:"requesting_user_id,omitempty"` // For isLiked field
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_proto_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetPostRequest) GetRequestingUserId() string {
	if x != nil && x.RequestingUserId != nil {
		return *x.RequestingUserId
	}
	return ""
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_proto_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpdatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_proto_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *DeletePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserPostsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	First            int32                  `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	After            *string                `protobuf:"bytes,3,opt,name=after,proto3,oneof" json:"after,omitempty"`
	RequestingUserId *string                `protobuf:"bytes,4,opt,name=requesting_user_id,json=requestingUserId,proto3,oneof" json:"requesting_user_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserPostsRequest) Reset() {
	*x = GetUserPostsRequest{}
	mi := &file_proto_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPostsRequest) ProtoMessage() {}

func (x *GetUserPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPostsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPostsRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserPostsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserPostsRequest) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *GetUserPostsRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *GetUserPostsRequest) GetRequestingUserId() string {
	if x != nil && x.RequestingUserId != nil {
		return *x.RequestingUserId
	}
	return ""
}

type IncrementCommentsCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementCommentsCountRequest) Reset() {
	*x = IncrementCommentsCountRequest{}
	mi := &file_proto_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementCommentsCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementCommentsCountRequest) ProtoMessage() {}

func (x *IncrementCommentsCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementCommentsCountRequest.ProtoReflect.Descriptor instead.
func (*IncrementCommentsCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{5}
}

func (x *IncrementCommentsCountRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type DecrementCommentsCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrementCommentsCountRequest) Reset() {
	*x = DecrementCommentsCountRequest{}
	mi := &file_proto_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrementCommentsCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementCommentsCountRequest) ProtoMessage() {}

func (x *DecrementCommentsCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementCommentsCountRequest.ProtoReflect.Descriptor instead.
func (*DecrementCommentsCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{6}
}

func (x *DecrementCommentsCountRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type IncrementLikesCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementLikesCountRequest) Reset() {
	*x = IncrementLikesCountRequest{}
	mi := &file_proto_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementLikesCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementLikesCountRequest) ProtoMessage() {}

func (x *IncrementLikesCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementLikesCountRequest.ProtoReflect.Descriptor instead.
func (*IncrementLikesCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{7}
}

func (x *IncrementLikesCountRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type DecrementLikesCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrementLikesCountRequest) Reset() {
	*x = DecrementLikesCountRequest{}
	mi := &file_proto_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrementLikesCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementLikesCountRequest) ProtoMessage() {}

func (x *DecrementLikesCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementLikesCountRequest.ProtoReflect.Descriptor instead.
func (*DecrementLikesCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{8}
}

func (x *DecrementLikesCountRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LikesCount    int32                  `protobuf:"varint,6,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	CommentsCount int32                  `protobuf:"varint,7,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	IsLiked       *bool                  `protobuf:"varint,8,opt,name=is_liked,json=isLiked,proto3,oneof" json:"is_liked,omitempty"` // Only set if requesting_user_id provided
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_proto_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{9}
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Post) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Post) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *Post) GetCommentsCount() int32 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *Post) GetIsLiked() bool {
	if x != nil && x.IsLiked != nil {
		return *x.IsLiked
	}
	return false
}

type PostEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Node          *Post                  `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostEdge) Reset() {
	*x = PostEdge{}
	mi := &file_proto_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostEdge) ProtoMessage() {}

func (x *PostEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostEdge.ProtoReflect.Descriptor instead.
func (*PostEdge) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{10}
}

func (x *PostEdge) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *PostEdge) GetNode() *Post {
	if x != nil {
		return x.Node
	}
	return nil
}

type PageInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EndCursor       *string                `protobuf:"bytes,1,opt,name=end_cursor,json=endCursor,proto3,oneof" json:"end_cursor,omitempty"`
	HasNextPage     bool                   `protobuf:"varint,2,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	StartCursor     *string                `protobuf:"bytes,3,opt,name=start_cursor,json=startCursor,proto3,oneof" json:"start_cursor,omitempty"`
	HasPreviousPage bool                   `protobuf:"varint,4,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_proto_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{11}
}

func (x *PageInfo) GetEndCursor() string {
	if x != nil && x.EndCursor != nil {
		return *x.EndCursor
	}
	return ""
}

func (x *PageInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *PageInfo) GetStartCursor() string {
	if x != nil && x.StartCursor != nil {
		return *x.StartCursor
	}
	return ""
}

func (x *PageInfo) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

type PostConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*PostEdge            `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostConnection) Reset() {
	*x = PostConnection{}
	mi := &file_proto_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostConnection) ProtoMessage() {}

func (x *PostConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostConnection.ProtoReflect.Descriptor instead.
func (*PostConnection) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{12}
}

func (x *PostConnection) GetEdges() []*PostEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *PostConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *PostConnection) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_post_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_post_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_post_proto_rawDescGZIP(), []int{13}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_post_proto protoreflect.FileDescriptor

const file_proto_post_proto_rawDesc = "" +
	"\n" +
	"\x10proto/post.proto\x12\x04post\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\x11CreatePostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"s\n" +
	"\x0eGetPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x121\n" +
	"\x12requesting_user_id\x18\x02 \x01(\tH\x00R\x10requestingUserId\x88\x01\x01B\x15\n" +
	"\x13_requesting_user_id\"_\n" +
	"\x11UpdatePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"E\n" +
	"\x11DeletePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xb3\x01\n" +
	"\x13GetUserPostsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05first\x18\x02 \x01(\x05R\x05first\x12\x19\n" +
	"\x05after\x18\x03 \x01(\tH\x00R\x05after\x88\x01\x01\x121\n" +
	"\x12requesting_user_id\x18\x04 \x01(\tH\x01R\x10requestingUserId\x88\x01\x01B\b\n" +
	"\x06_afterB\x15\n" +
	"\x13_requesting_user_id\"8\n" +
	"\x1dIncrementCommentsCountRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"8\n" +
	"\x1dDecrementCommentsCountRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"5\n" +
	"\x1aIncrementLikesCountRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"5\n" +
	"\x1aDecrementLikesCountRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"\xb4\x02\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vlikes_count\x18\x06 \x01(\x05R\n" +
	"likesCount\x12%\n" +
	"\x0ecomments_count\x18\a \x01(\x05R\rcommentsCount\x12\x1e\n" +
	"\bis_liked\x18\b \x01(\bH\x00R\aisLiked\x88\x01\x01B\v\n" +
	"\t_is_liked\"B\n" +
	"\bPostEdge\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x1e\n" +
	"\x04node\x18\x02 \x01(\v2\n" +
	".post.PostR\x04node\"\xc6\x01\n" +
	"\bPageInfo\x12\"\n" +
	"\n" +
	"end_cursor\x18\x01 \x01(\tH\x00R\tendCursor\x88\x01\x01\x12\"\n" +
	"\rhas_next_page\x18\x02 \x01(\bR\vhasNextPage\x12&\n" +
	"\fstart_cursor\x18\x03 \x01(\tH\x01R\vstartCursor\x88\x01\x01\x12*\n" +
	"\x11has_previous_page\x18\x04 \x01(\bR\x0fhasPreviousPageB\r\n" +
	"\v_end_cursorB\x0f\n" +
	"\r_start_cursor\"\x84\x01\n" +
	"\x0ePostConnection\x12$\n" +
	"\x05edges\x18\x01 \x03(\v2\x0e.post.PostEdgeR\x05edges\x12+\n" +
	"\tpage_info\x18\x02 \x01(\v2\x0e.post.PageInfoR\bpageInfo\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc8\x04\n" +
	"\vPostService\x121\n" +
	"\n" +
	"CreatePost\x12\x17.post.CreatePostRequest\x1a\n" +
	".post.Post\x12+\n" +
	"\aGetPost\x12\x14.post.GetPostRequest\x1a\n" +
	".post.Post\x121\n" +
	"\n" +
	"UpdatePost\x12\x17.post.UpdatePostRequest\x1a\n" +
	".post.Post\x125\n" +
	"\n" +
	"DeletePost\x12\x17.post.DeletePostRequest\x1a\x0e.post.Response\x12?\n" +
	"\fGetUserPosts\x12\x19.post.GetUserPostsRequest\x1a\x14.post.PostConnection\x12M\n" +
	"\x16IncrementCommentsCount\x12#.post.IncrementCommentsCountRequest\x1a\x0e.post.Response\x12M\n" +
	"\x16DecrementCommentsCount\x12#.post.DecrementCommentsCountRequest\x1a\x0e.post.Response\x12G\n" +
	"\x13IncrementLikesCount\x12 .post.IncrementLikesCountRequest\x1a\x0e.post.Response\x12G\n" +
	"\x13DecrementLikesCount\x12 .post.DecrementLikesCountRequest\x1a\x0e.post.ResponseB\x04Z\x02./b\x06proto3"

var (
	file_proto_post_proto_rawDescOnce sync.Once
	file_proto_post_proto_rawDescData []byte
)

func file_proto_post_proto_rawDescGZIP() []byte {
	file_proto_post_proto_rawDescOnce.Do(func() {
		file_proto_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_post_proto_rawDesc), len(file_proto_post_proto_rawDesc)))
	})
	return file_proto_post_proto_rawDescData
}

var file_proto_post_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_post_proto_goTypes = []any{
	(*CreatePostRequest)(nil),             // 0: post.CreatePostRequest
	(*GetPostRequest)(nil),                // 1: post.GetPostRequest
	(*UpdatePostRequest)(nil),             // 2: post.UpdatePostRequest
	(*DeletePostRequest)(nil),             // 3: post.DeletePostRequest
	(*GetUserPostsRequest)(nil),           // 4: post.GetUserPostsRequest
	(*IncrementCommentsCountRequest)(nil), // 5: post.IncrementCommentsCountRequest
	(*DecrementCommentsCountRequest)(nil), // 6: post.DecrementCommentsCountRequest
	(*IncrementLikesCountRequest)(nil),    // 7: post.IncrementLikesCountRequest
	(*DecrementLikesCountRequest)(nil),    // 8: post.DecrementLikesCountRequest
	(*Post)(nil),                          // 9: post.Post
	(*PostEdge)(nil),                      // 10: post.PostEdge
	(*PageInfo)(nil),                      // 11: post.PageInfo
	(*PostConnection)(nil),                // 12: post.PostConnection
	(*Response)(nil),                      // 13: post.Response
	(*timestamppb.Timestamp)(nil),         // 14: google.protobuf.Timestamp
}
var file_proto_post_proto_depIdxs = []int32{
	14, // 0: post.Post.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: post.Post.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: post.PostEdge.node:type_name -> post.Post
	10, // 3: post.PostConnection.edges:type_name -> post.PostEdge
	11, // 4: post.PostConnection.page_info:type_name -> post.PageInfo
	0,  // 5: post.PostService.CreatePost:input_type -> post.CreatePostRequest
	1,  // 6: post.PostService.GetPost:input_type -> post.GetPostRequest
	2,  // 7: post.PostService.UpdatePost:input_type -> post.UpdatePostRequest
	3,  // 8: post.PostService.DeletePost:input_type -> post.DeletePostRequest
	4,  // 9: post.PostService.GetUserPosts:input_type -> post.GetUserPostsRequest
	5,  // 10: post.PostService.IncrementCommentsCount:input_type -> post.IncrementCommentsCountRequest
	6,  // 11: post.PostService.DecrementCommentsCount:input_type -> post.DecrementCommentsCountRequest
	7,  // 12: post.PostService.IncrementLikesCount:input_type -> post.IncrementLikesCountRequest
	8,  // 13: post.PostService.DecrementLikesCount:input_type -> post.DecrementLikesCountRequest
	9,  // 14: post.PostService.CreatePost:output_type -> post.Post
	9,  // 15: post.PostService.GetPost:output_type -> post.Post
	9,  // 16: post.PostService.UpdatePost:output_type -> post.Post
	13, // 17: post.PostService.DeletePost:output_type -> post.Response
	12, // 18: post.PostService.GetUserPosts:output_type -> post.PostConnection
	13, // 19: post.PostService.IncrementCommentsCount:output_type -> post.Response
	13, // 20: post.PostService.DecrementCommentsCount:output_type -> post.Response
	13, // 21: post.PostService.IncrementLikesCount:output_type -> post.Response
	13, // 22: post.PostService.DecrementLikesCount:output_type -> post.Response
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_post_proto_init() }
func file_proto_post_proto_init() {
	if File_proto_post_proto != nil {
		return
	}
	file_proto_post_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_post_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_post_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_post_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_post_proto_rawDesc), len(file_proto_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_post_proto_goTypes,
		DependencyIndexes: file_proto_post_proto_depIdxs,
		MessageInfos:      file_proto_post_proto_msgTypes,
	}.Build()
	File_proto_post_proto = out.File
	file_proto_post_proto_goTypes = nil
	file_proto_post_proto_depIdxs = nil
}
