// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/notification.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	NotificationType_POST                          NotificationType = 1
	NotificationType_COMMENT                       NotificationType = 2
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "POST",
		2: "COMMENT",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED": 0,
		"POST":                          1,
		"COMMENT":                       2,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_proto_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{0}
}

type GetNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	First         int32                  `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	After         *string                `protobuf:"bytes,3,opt,name=after,proto3,oneof" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsRequest) Reset() {
	*x = GetNotificationsRequest{}
	mi := &file_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsRequest) ProtoMessage() {}

func (x *GetNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *GetNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetNotificationsRequest) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *GetNotificationsRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

type MarkReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *MarkReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *MarkReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MarkAllReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllReadRequest) Reset() {
	*x = MarkAllReadRequest{}
	mi := &file_proto_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllReadRequest) ProtoMessage() {}

func (x *MarkAllReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{2}
}

func (x *MarkAllReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ActorId       *string                `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3,oneof" json:"actor_id,omitempty"`
	RelatedId     *string                `protobuf:"bytes,5,opt,name=related_id,json=relatedId,proto3,oneof" json:"related_id,omitempty"` // postId, commentId, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_proto_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *CreateNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateNotificationRequest) GetActorId() string {
	if x != nil && x.ActorId != nil {
		return *x.ActorId
	}
	return ""
}

func (x *CreateNotificationRequest) GetRelatedId() string {
	if x != nil && x.RelatedId != nil {
		return *x.RelatedId
	}
	return ""
}

type DeleteNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_proto_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          NotificationType       `protobuf:"varint,3,opt,name=type,proto3,enum=notification.NotificationType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ActorId       *string                `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3,oneof" json:"actor_id,omitempty"`
	RelatedId     *string                `protobuf:"bytes,6,opt,name=related_id,json=relatedId,proto3,oneof" json:"related_id,omitempty"`
	IsRead        bool                   `protobuf:"varint,7,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{5}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetActorId() string {
	if x != nil && x.ActorId != nil {
		return *x.ActorId
	}
	return ""
}

func (x *Notification) GetRelatedId() string {
	if x != nil && x.RelatedId != nil {
		return *x.RelatedId
	}
	return ""
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type NotificationEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Node          *Notification          `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEdge) Reset() {
	*x = NotificationEdge{}
	mi := &file_proto_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEdge) ProtoMessage() {}

func (x *NotificationEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEdge.ProtoReflect.Descriptor instead.
func (*NotificationEdge) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{6}
}

func (x *NotificationEdge) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *NotificationEdge) GetNode() *Notification {
	if x != nil {
		return x.Node
	}
	return nil
}

type PageInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EndCursor       *string                `protobuf:"bytes,1,opt,name=end_cursor,json=endCursor,proto3,oneof" json:"end_cursor,omitempty"`
	HasNextPage     bool                   `protobuf:"varint,2,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	StartCursor     *string                `protobuf:"bytes,3,opt,name=start_cursor,json=startCursor,proto3,oneof" json:"start_cursor,omitempty"`
	HasPreviousPage bool                   `protobuf:"varint,4,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_proto_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{7}
}

func (x *PageInfo) GetEndCursor() string {
	if x != nil && x.EndCursor != nil {
		return *x.EndCursor
	}
	return ""
}

func (x *PageInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *PageInfo) GetStartCursor() string {
	if x != nil && x.StartCursor != nil {
		return *x.StartCursor
	}
	return ""
}

func (x *PageInfo) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

type NotificationConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*NotificationEdge    `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,4,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationConnection) Reset() {
	*x = NotificationConnection{}
	mi := &file_proto_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationConnection) ProtoMessage() {}

func (x *NotificationConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationConnection.ProtoReflect.Descriptor instead.
func (*NotificationConnection) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{8}
}

func (x *NotificationConnection) GetEdges() []*NotificationEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *NotificationConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *NotificationConnection) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *NotificationConnection) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{9}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_notification_proto protoreflect.FileDescriptor

const file_proto_notification_proto_rawDesc = "" +
	"\n" +
	"\x18proto/notification.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\"m\n" +
	"\x17GetNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05first\x18\x02 \x01(\x05R\x05first\x12\x19\n" +
	"\x05after\x18\x03 \x01(\tH\x00R\x05after\x88\x01\x01B\b\n" +
	"\x06_after\"S\n" +
	"\x0fMarkReadRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"-\n" +
	"\x12MarkAllReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xe2\x01\n" +
	"\x19CreateNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.notification.NotificationTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1e\n" +
	"\bactor_id\x18\x04 \x01(\tH\x00R\aactorId\x88\x01\x01\x12\"\n" +
	"\n" +
	"related_id\x18\x05 \x01(\tH\x01R\trelatedId\x88\x01\x01B\v\n" +
	"\t_actor_idB\r\n" +
	"\v_related_id\"D\n" +
	"\x19DeleteNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"\xb9\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.notification.NotificationTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1e\n" +
	"\bactor_id\x18\x05 \x01(\tH\x00R\aactorId\x88\x01\x01\x12\"\n" +
	"\n" +
	"related_id\x18\x06 \x01(\tH\x01R\trelatedId\x88\x01\x01\x12\x17\n" +
	"\ais_read\x18\a \x01(\bR\x06isRead\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\v\n" +
	"\t_actor_idB\r\n" +
	"\v_related_id\"Z\n" +
	"\x10NotificationEdge\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12.\n" +
	"\x04node\x18\x02 \x01(\v2\x1a.notification.NotificationR\x04node\"\xc6\x01\n" +
	"\bPageInfo\x12\"\n" +
	"\n" +
	"end_cursor\x18\x01 \x01(\tH\x00R\tendCursor\x88\x01\x01\x12\"\n" +
	"\rhas_next_page\x18\x02 \x01(\bR\vhasNextPage\x12&\n" +
	"\fstart_cursor\x18\x03 \x01(\tH\x01R\vstartCursor\x88\x01\x01\x12*\n" +
	"\x11has_previous_page\x18\x04 \x01(\bR\x0fhasPreviousPageB\r\n" +
	"\v_end_cursorB\x0f\n" +
	"\r_start_cursor\"\xc7\x01\n" +
	"\x16NotificationConnection\x124\n" +
	"\x05edges\x18\x01 \x03(\v2\x1e.notification.NotificationEdgeR\x05edges\x123\n" +
	"\tpage_info\x18\x02 \x01(\v2\x16.notification.PageInfoR\bpageInfo\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\funread_count\x18\x04 \x01(\x05R\vunreadCount\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*L\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04POST\x10\x01\x12\v\n" +
	"\aCOMMENT\x10\x022\xb4\x03\n" +
	"\x13NotificationService\x12_\n" +
	"\x10GetNotifications\x12%.notification.GetNotificationsRequest\x1a$.notification.NotificationConnection\x12A\n" +
	"\bMarkRead\x12\x1d.notification.MarkReadRequest\x1a\x16.notification.Response\x12G\n" +
	"\vMarkAllRead\x12 .notification.MarkAllReadRequest\x1a\x16.notification.Response\x12Y\n" +
	"\x12CreateNotification\x12'.notification.CreateNotificationRequest\x1a\x1a.notification.Notification\x12U\n" +
	"\x12DeleteNotification\x12'.notification.DeleteNotificationRequest\x1a\x16.notification.ResponseB\x04Z\x02./b\x06proto3"

var (
	file_proto_notification_proto_rawDescOnce sync.Once
	file_proto_notification_proto_rawDescData []byte
)

func file_proto_notification_proto_rawDescGZIP() []byte {
	file_proto_notification_proto_rawDescOnce.Do(func() {
		file_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)))
	})
	return file_proto_notification_proto_rawDescData
}

var file_proto_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_notification_proto_goTypes = []any{
	(NotificationType)(0),             // 0: notification.NotificationType
	(*GetNotificationsRequest)(nil),   // 1: notification.GetNotificationsRequest
	(*MarkReadRequest)(nil),           // 2: notification.MarkReadRequest
	(*MarkAllReadRequest)(nil),        // 3: notification.MarkAllReadRequest
	(*CreateNotificationRequest)(nil), // 4: notification.CreateNotificationRequest
	(*DeleteNotificationRequest)(nil), // 5: notification.DeleteNotificationRequest
	(*Notification)(nil),              // 6: notification.Notification
	(*NotificationEdge)(nil),          // 7: notification.NotificationEdge
	(*PageInfo)(nil),                  // 8: notification.PageInfo
	(*NotificationConnection)(nil),    // 9: notification.NotificationConnection
	(*Response)(nil),                  // 10: notification.Response
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_proto_notification_proto_depIdxs = []int32{
	0,  // 0: notification.CreateNotificationRequest.type:type_name -> notification.NotificationType
	0,  // 1: notification.Notification.type:type_name -> notification.NotificationType
	11, // 2: notification.Notification.created_at:type_name -> google.protobuf.Timestamp
	6,  // 3: notification.NotificationEdge.node:type_name -> notification.Notification
	7,  // 4: notification.NotificationConnection.edges:type_name -> notification.NotificationEdge
	8,  // 5: notification.NotificationConnection.page_info:type_name -> notification.PageInfo
	1,  // 6: notification.NotificationService.GetNotifications:input_type -> notification.GetNotificationsRequest
	2,  // 7: notification.NotificationService.MarkRead:input_type -> notification.MarkReadRequest
	3,  // 8: notification.NotificationService.MarkAllRead:input_type -> notification.MarkAllReadRequest
	4,  // 9: notification.NotificationService.CreateNotification:input_type -> notification.CreateNotificationRequest
	5,  // 10: notification.NotificationService.DeleteNotification:input_type -> notification.DeleteNotificationRequest
	9,  // 11: notification.NotificationService.GetNotifications:output_type -> notification.NotificationConnection
	10, // 12: notification.NotificationService.MarkRead:output_type -> notification.Response
	10, // 13: notification.NotificationService.MarkAllRead:output_type -> notification.Response
	6,  // 14: notification.NotificationService.CreateNotification:output_type -> notification.Notification
	10, // 15: notification.NotificationService.DeleteNotification:output_type -> notification.Response
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_notification_proto_init() }
func file_proto_notification_proto_init() {
	if File_proto_notification_proto != nil {
		return
	}
	file_proto_notification_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_notification_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_notification_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_notification_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notification_proto_goTypes,
		DependencyIndexes: file_proto_notification_proto_depIdxs,
		EnumInfos:         file_proto_notification_proto_enumTypes,
		MessageInfos:      file_proto_notification_proto_msgTypes,
	}.Build()
	File_proto_notification_proto = out.File
	file_proto_notification_proto_goTypes = nil
	file_proto_notification_proto_depIdxs = nil
}
