// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/follow.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`    // User who is following
	FollowingId   string                 `protobuf:"bytes,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"` // User being followed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_proto_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{0}
}

func (x *FollowUserRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowUserRequest) GetFollowingId() string {
	if x != nil {
		return x.FollowingId
	}
	return ""
}

type UnfollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowingId   string                 `protobuf:"bytes,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserRequest) Reset() {
	*x = UnfollowUserRequest{}
	mi := &file_proto_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserRequest) ProtoMessage() {}

func (x *UnfollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserRequest.ProtoReflect.Descriptor instead.
func (*UnfollowUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{1}
}

func (x *UnfollowUserRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *UnfollowUserRequest) GetFollowingId() string {
	if x != nil {
		return x.FollowingId
	}
	return ""
}

type GetFollowersRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	First            int32                  `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	After            *string                `protobuf:"bytes,3,opt,name=after,proto3,oneof" json:"after,omitempty"`
	RequestingUserId *string                `protobuf:"bytes,4,opt,name=requesting_user_id,json=requestingUserId,proto3,oneof" json:"requesting_user_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_proto_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFollowersRequest) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *GetFollowersRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *GetFollowersRequest) GetRequestingUserId() string {
	if x != nil && x.RequestingUserId != nil {
		return *x.RequestingUserId
	}
	return ""
}

type GetFollowingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	First            int32                  `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	After            *string                `protobuf:"bytes,3,opt,name=after,proto3,oneof" json:"after,omitempty"`
	RequestingUserId *string                `protobuf:"bytes,4,opt,name=requesting_user_id,json=requestingUserId,proto3,oneof" json:"requesting_user_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_proto_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{3}
}

func (x *GetFollowingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFollowingRequest) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *GetFollowingRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *GetFollowingRequest) GetRequestingUserId() string {
	if x != nil && x.RequestingUserId != nil {
		return *x.RequestingUserId
	}
	return ""
}

type IsFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowingId   string                 `protobuf:"bytes,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingRequest) Reset() {
	*x = IsFollowingRequest{}
	mi := &file_proto_follow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingRequest) ProtoMessage() {}

func (x *IsFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingRequest.ProtoReflect.Descriptor instead.
func (*IsFollowingRequest) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{4}
}

func (x *IsFollowingRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *IsFollowingRequest) GetFollowingId() string {
	if x != nil {
		return x.FollowingId
	}
	return ""
}

type IsFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFollowing   bool                   `protobuf:"varint,1,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingResponse) Reset() {
	*x = IsFollowingResponse{}
	mi := &file_proto_follow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingResponse) ProtoMessage() {}

func (x *IsFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingResponse.ProtoReflect.Descriptor instead.
func (*IsFollowingResponse) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{5}
}

func (x *IsFollowingResponse) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type GetFollowStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserIds []string               `protobuf:"bytes,2,rep,name=target_user_ids,json=targetUserIds,proto3" json:"target_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowStatusRequest) Reset() {
	*x = GetFollowStatusRequest{}
	mi := &file_proto_follow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowStatusRequest) ProtoMessage() {}

func (x *GetFollowStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowStatusRequest.ProtoReflect.Descriptor instead.
func (*GetFollowStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{6}
}

func (x *GetFollowStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFollowStatusRequest) GetTargetUserIds() []string {
	if x != nil {
		return x.TargetUserIds
	}
	return nil
}

type FollowStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsFollowing   bool                   `protobuf:"varint,2,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowStatus) Reset() {
	*x = FollowStatus{}
	mi := &file_proto_follow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowStatus) ProtoMessage() {}

func (x *FollowStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowStatus.ProtoReflect.Descriptor instead.
func (*FollowStatus) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{7}
}

func (x *FollowStatus) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FollowStatus) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type GetFollowStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*FollowStatus        `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowStatusResponse) Reset() {
	*x = GetFollowStatusResponse{}
	mi := &file_proto_follow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowStatusResponse) ProtoMessage() {}

func (x *GetFollowStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowStatusResponse.ProtoReflect.Descriptor instead.
func (*GetFollowStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{8}
}

func (x *GetFollowStatusResponse) GetStatuses() []*FollowStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type GetFollowersCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersCountsRequest) Reset() {
	*x = GetFollowersCountsRequest{}
	mi := &file_proto_follow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersCountsRequest) ProtoMessage() {}

func (x *GetFollowersCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersCountsRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersCountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{9}
}

func (x *GetFollowersCountsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type UserFollowCounts struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowersCount int32                  `protobuf:"varint,2,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	FollowingCount int32                  `protobuf:"varint,3,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserFollowCounts) Reset() {
	*x = UserFollowCounts{}
	mi := &file_proto_follow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFollowCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFollowCounts) ProtoMessage() {}

func (x *UserFollowCounts) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFollowCounts.ProtoReflect.Descriptor instead.
func (*UserFollowCounts) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{10}
}

func (x *UserFollowCounts) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFollowCounts) GetFollowersCount() int32 {
	if x != nil {
		return x.FollowersCount
	}
	return 0
}

func (x *UserFollowCounts) GetFollowingCount() int32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

type GetFollowersCountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        []*UserFollowCounts    `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersCountsResponse) Reset() {
	*x = GetFollowersCountsResponse{}
	mi := &file_proto_follow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersCountsResponse) ProtoMessage() {}

func (x *GetFollowersCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersCountsResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersCountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{11}
}

func (x *GetFollowersCountsResponse) GetCounts() []*UserFollowCounts {
	if x != nil {
		return x.Counts
	}
	return nil
}

type FollowEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=followed_at,json=followedAt,proto3" json:"followed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowEdge) Reset() {
	*x = FollowEdge{}
	mi := &file_proto_follow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowEdge) ProtoMessage() {}

func (x *FollowEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowEdge.ProtoReflect.Descriptor instead.
func (*FollowEdge) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{12}
}

func (x *FollowEdge) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *FollowEdge) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FollowEdge) GetFollowedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FollowedAt
	}
	return nil
}

type PageInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EndCursor       *string                `protobuf:"bytes,1,opt,name=end_cursor,json=endCursor,proto3,oneof" json:"end_cursor,omitempty"`
	HasNextPage     bool                   `protobuf:"varint,2,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	StartCursor     *string                `protobuf:"bytes,3,opt,name=start_cursor,json=startCursor,proto3,oneof" json:"start_cursor,omitempty"`
	HasPreviousPage bool                   `protobuf:"varint,4,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_proto_follow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{13}
}

func (x *PageInfo) GetEndCursor() string {
	if x != nil && x.EndCursor != nil {
		return *x.EndCursor
	}
	return ""
}

func (x *PageInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *PageInfo) GetStartCursor() string {
	if x != nil && x.StartCursor != nil {
		return *x.StartCursor
	}
	return ""
}

func (x *PageInfo) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

type FollowConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*FollowEdge          `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowConnection) Reset() {
	*x = FollowConnection{}
	mi := &file_proto_follow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowConnection) ProtoMessage() {}

func (x *FollowConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowConnection.ProtoReflect.Descriptor instead.
func (*FollowConnection) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{14}
}

func (x *FollowConnection) GetEdges() []*FollowEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *FollowConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *FollowConnection) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_follow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{15}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_follow_proto protoreflect.FileDescriptor

const file_proto_follow_proto_rawDesc = "" +
	"\n" +
	"\x12proto/follow.proto\x12\x06follow\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n" +
	"\x11FollowUserRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\tR\vfollowingId\"Y\n" +
	"\x13UnfollowUserRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\tR\vfollowingId\"\xb3\x01\n" +
	"\x13GetFollowersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05first\x18\x02 \x01(\x05R\x05first\x12\x19\n" +
	"\x05after\x18\x03 \x01(\tH\x00R\x05after\x88\x01\x01\x121\n" +
	"\x12requesting_user_id\x18\x04 \x01(\tH\x01R\x10requestingUserId\x88\x01\x01B\b\n" +
	"\x06_afterB\x15\n" +
	"\x13_requesting_user_id\"\xb3\x01\n" +
	"\x13GetFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05first\x18\x02 \x01(\x05R\x05first\x12\x19\n" +
	"\x05after\x18\x03 \x01(\tH\x00R\x05after\x88\x01\x01\x121\n" +
	"\x12requesting_user_id\x18\x04 \x01(\tH\x01R\x10requestingUserId\x88\x01\x01B\b\n" +
	"\x06_afterB\x15\n" +
	"\x13_requesting_user_id\"X\n" +
	"\x12IsFollowingRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\tR\vfollowingId\"8\n" +
	"\x13IsFollowingResponse\x12!\n" +
	"\fis_following\x18\x01 \x01(\bR\visFollowing\"Y\n" +
	"\x16GetFollowStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0ftarget_user_ids\x18\x02 \x03(\tR\rtargetUserIds\"J\n" +
	"\fFollowStatus\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fis_following\x18\x02 \x01(\bR\visFollowing\"K\n" +
	"\x17GetFollowStatusResponse\x120\n" +
	"\bstatuses\x18\x01 \x03(\v2\x14.follow.FollowStatusR\bstatuses\"6\n" +
	"\x19GetFollowersCountsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"}\n" +
	"\x10UserFollowCounts\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0ffollowers_count\x18\x02 \x01(\x05R\x0efollowersCount\x12'\n" +
	"\x0ffollowing_count\x18\x03 \x01(\x05R\x0efollowingCount\"N\n" +
	"\x1aGetFollowersCountsResponse\x120\n" +
	"\x06counts\x18\x01 \x03(\v2\x18.follow.UserFollowCountsR\x06counts\"z\n" +
	"\n" +
	"FollowEdge\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12;\n" +
	"\vfollowed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"followedAt\"\xc6\x01\n" +
	"\bPageInfo\x12\"\n" +
	"\n" +
	"end_cursor\x18\x01 \x01(\tH\x00R\tendCursor\x88\x01\x01\x12\"\n" +
	"\rhas_next_page\x18\x02 \x01(\bR\vhasNextPage\x12&\n" +
	"\fstart_cursor\x18\x03 \x01(\tH\x01R\vstartCursor\x88\x01\x01\x12*\n" +
	"\x11has_previous_page\x18\x04 \x01(\bR\x0fhasPreviousPageB\r\n" +
	"\v_end_cursorB\x0f\n" +
	"\r_start_cursor\"\x8c\x01\n" +
	"\x10FollowConnection\x12(\n" +
	"\x05edges\x18\x01 \x03(\v2\x12.follow.FollowEdgeR\x05edges\x12-\n" +
	"\tpage_info\x18\x02 \x01(\v2\x10.follow.PageInfoR\bpageInfo\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x90\x04\n" +
	"\rFollowService\x129\n" +
	"\n" +
	"FollowUser\x12\x19.follow.FollowUserRequest\x1a\x10.follow.Response\x12=\n" +
	"\fUnfollowUser\x12\x1b.follow.UnfollowUserRequest\x1a\x10.follow.Response\x12E\n" +
	"\fGetFollowers\x12\x1b.follow.GetFollowersRequest\x1a\x18.follow.FollowConnection\x12E\n" +
	"\fGetFollowing\x12\x1b.follow.GetFollowingRequest\x1a\x18.follow.FollowConnection\x12F\n" +
	"\vIsFollowing\x12\x1a.follow.IsFollowingRequest\x1a\x1b.follow.IsFollowingResponse\x12R\n" +
	"\x0fGetFollowStatus\x12\x1e.follow.GetFollowStatusRequest\x1a\x1f.follow.GetFollowStatusResponse\x12[\n" +
	"\x12GetFollowersCounts\x12!.follow.GetFollowersCountsRequest\x1a\".follow.GetFollowersCountsResponseB\x04Z\x02./b\x06proto3"

var (
	file_proto_follow_proto_rawDescOnce sync.Once
	file_proto_follow_proto_rawDescData []byte
)

func file_proto_follow_proto_rawDescGZIP() []byte {
	file_proto_follow_proto_rawDescOnce.Do(func() {
		file_proto_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_follow_proto_rawDesc), len(file_proto_follow_proto_rawDesc)))
	})
	return file_proto_follow_proto_rawDescData
}

var file_proto_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_follow_proto_goTypes = []any{
	(*FollowUserRequest)(nil),          // 0: follow.FollowUserRequest
	(*UnfollowUserRequest)(nil),        // 1: follow.UnfollowUserRequest
	(*GetFollowersRequest)(nil),        // 2: follow.GetFollowersRequest
	(*GetFollowingRequest)(nil),        // 3: follow.GetFollowingRequest
	(*IsFollowingRequest)(nil),         // 4: follow.IsFollowingRequest
	(*IsFollowingResponse)(nil),        // 5: follow.IsFollowingResponse
	(*GetFollowStatusRequest)(nil),     // 6: follow.GetFollowStatusRequest
	(*FollowStatus)(nil),               // 7: follow.FollowStatus
	(*GetFollowStatusResponse)(nil),    // 8: follow.GetFollowStatusResponse
	(*GetFollowersCountsRequest)(nil),  // 9: follow.GetFollowersCountsRequest
	(*UserFollowCounts)(nil),           // 10: follow.UserFollowCounts
	(*GetFollowersCountsResponse)(nil), // 11: follow.GetFollowersCountsResponse
	(*FollowEdge)(nil),                 // 12: follow.FollowEdge
	(*PageInfo)(nil),                   // 13: follow.PageInfo
	(*FollowConnection)(nil),           // 14: follow.FollowConnection
	(*Response)(nil),                   // 15: follow.Response
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
}
var file_proto_follow_proto_depIdxs = []int32{
	7,  // 0: follow.GetFollowStatusResponse.statuses:type_name -> follow.FollowStatus
	10, // 1: follow.GetFollowersCountsResponse.counts:type_name -> follow.UserFollowCounts
	16, // 2: follow.FollowEdge.followed_at:type_name -> google.protobuf.Timestamp
	12, // 3: follow.FollowConnection.edges:type_name -> follow.FollowEdge
	13, // 4: follow.FollowConnection.page_info:type_name -> follow.PageInfo
	0,  // 5: follow.FollowService.FollowUser:input_type -> follow.FollowUserRequest
	1,  // 6: follow.FollowService.UnfollowUser:input_type -> follow.UnfollowUserRequest
	2,  // 7: follow.FollowService.GetFollowers:input_type -> follow.GetFollowersRequest
	3,  // 8: follow.FollowService.GetFollowing:input_type -> follow.GetFollowingRequest
	4,  // 9: follow.FollowService.IsFollowing:input_type -> follow.IsFollowingRequest
	6,  // 10: follow.FollowService.GetFollowStatus:input_type -> follow.GetFollowStatusRequest
	9,  // 11: follow.FollowService.GetFollowersCounts:input_type -> follow.GetFollowersCountsRequest
	15, // 12: follow.FollowService.FollowUser:output_type -> follow.Response
	15, // 13: follow.FollowService.UnfollowUser:output_type -> follow.Response
	14, // 14: follow.FollowService.GetFollowers:output_type -> follow.FollowConnection
	14, // 15: follow.FollowService.GetFollowing:output_type -> follow.FollowConnection
	5,  // 16: follow.FollowService.IsFollowing:output_type -> follow.IsFollowingResponse
	8,  // 17: follow.FollowService.GetFollowStatus:output_type -> follow.GetFollowStatusResponse
	11, // 18: follow.FollowService.GetFollowersCounts:output_type -> follow.GetFollowersCountsResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_follow_proto_init() }
func file_proto_follow_proto_init() {
	if File_proto_follow_proto != nil {
		return
	}
	file_proto_follow_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_follow_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_follow_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_follow_proto_rawDesc), len(file_proto_follow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_follow_proto_goTypes,
		DependencyIndexes: file_proto_follow_proto_depIdxs,
		MessageInfos:      file_proto_follow_proto_msgTypes,
	}.Build()
	File_proto_follow_proto = out.File
	file_proto_follow_proto_goTypes = nil
	file_proto_follow_proto_depIdxs = nil
}
